/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ApiEscalationsRouteImport } from './routes/api/escalations'
import { Route as ApiLivekitTokenRouteImport } from './routes/api/livekit-token'
import { Route as ApiRequestCallRouteImport } from './routes/api/request-call'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEscalationsRoute = ApiEscalationsRouteImport.update({
  id: '/api/escalations',
  path: '/api/escalations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLivekitTokenRoute = ApiLivekitTokenRouteImport.update({
  id: '/api/livekit-token',
  path: '/api/livekit-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRequestCallRoute = ApiRequestCallRouteImport.update({
  id: '/api/request-call',
  path: '/api/request-call',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/support': typeof SupportRoute
  '/api/escalations': typeof ApiEscalationsRoute
  '/api/livekit-token': typeof ApiLivekitTokenRoute
  '/api/request-call': typeof ApiRequestCallRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/support': typeof SupportRoute
  '/api/escalations': typeof ApiEscalationsRoute
  '/api/livekit-token': typeof ApiLivekitTokenRoute
  '/api/request-call': typeof ApiRequestCallRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/support': typeof SupportRoute
  '/api/escalations': typeof ApiEscalationsRoute
  '/api/livekit-token': typeof ApiLivekitTokenRoute
  '/api/request-call': typeof ApiRequestCallRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/support'
    | '/api/escalations'
    | '/api/livekit-token'
    | '/api/request-call'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/support'
    | '/api/escalations'
    | '/api/livekit-token'
    | '/api/request-call'
  id:
    | '__root__'
    | '/'
    | '/support'
    | '/api/escalations'
    | '/api/livekit-token'
    | '/api/request-call'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SupportRoute: typeof SupportRoute
  ApiEscalationsRoute: typeof ApiEscalationsRoute
  ApiLivekitTokenRoute: typeof ApiLivekitTokenRoute
  ApiRequestCallRoute: typeof ApiRequestCallRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/escalations': {
      id: '/api/escalations'
      path: '/api/escalations'
      fullPath: '/api/escalations'
      preLoaderRoute: typeof ApiEscalationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/livekit-token': {
      id: '/api/livekit-token'
      path: '/api/livekit-token'
      fullPath: '/api/livekit-token'
      preLoaderRoute: typeof ApiLivekitTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/request-call': {
      id: '/api/request-call'
      path: '/api/request-call'
      fullPath: '/api/request-call'
      preLoaderRoute: typeof ApiRequestCallRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SupportRoute: SupportRoute,
  ApiEscalationsRoute: ApiEscalationsRoute,
  ApiLivekitTokenRoute: ApiLivekitTokenRoute,
  ApiRequestCallRoute: ApiRequestCallRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
